name: "Build Android APK"
description: "Builds the Android APK and shows info about the built artifact"
inputs:
  gradle-task:
    description: "Gradle task to run"
    required: false
    default: "assembleDebug"
outputs:
  apk-path:
    description: "The path to the built APK"
runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"

    - name: Build APK
      run: ./gradlew ${{ inputs.gradle-task }}

    - name: Find APK
      id: find_apk
      shell: bash
      run: |
        APK_PATH=$(find $PWD -type f -name "*.apk" | head -n 1)
        echo "apk-path=$APK_PATH" >> $GITHUB_OUTPUT
        echo "Built APK: $APK_PATH"

    - name: Show APK Info
      if: steps.find_apk.outputs.apk-path != ''
      run: |
        ls -lh "${{ steps.find_apk.outputs.apk-path }}"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: ${{ steps.find_apk.outputs.apk-path }}
